"""empty message

Revision ID: 4344786d44f0
Revises: 
Create Date: 2025-06-04 23:58:39.525059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4344786d44f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_class',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('instructor', sa.String(length=100), nullable=False),
    sa.Column('available_slots', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_email', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['fitness_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Bookings')
    op.drop_table('fitness_class')
    # ### end Alembic commands ###
